### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by worker8** [worker8/newp#1]
![](http://www.cutestpaw.com/wp-content/uploads/2013/04/Alpaca-in-the-snow.jpg)

- [ ] wrap with `ViewModel`
- [ ] Add tests
- [ ] Login user flow
- [ ] Home page UI
- [ ] Comment Swipe UI
   - [ ] ViewPager
   - [ ] Nested Comment View
- [ ] Settings page
- [ ] Style guide
